// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gate_msg.proto

package gate_msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StreamGateMessage struct {
	Body       []byte `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	ServerName string `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	MethodName string `protobuf:"bytes,3,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	// Types that are valid to be assigned to Kind:
	//	*StreamGateMessage_Json
	//	*StreamGateMessage_Protobuf
	Kind                 isStreamGateMessage_Kind `protobuf_oneof:"kind"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *StreamGateMessage) Reset()         { *m = StreamGateMessage{} }
func (m *StreamGateMessage) String() string { return proto.CompactTextString(m) }
func (*StreamGateMessage) ProtoMessage()    {}
func (*StreamGateMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40534712610c588, []int{0}
}

func (m *StreamGateMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamGateMessage.Unmarshal(m, b)
}
func (m *StreamGateMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamGateMessage.Marshal(b, m, deterministic)
}
func (m *StreamGateMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamGateMessage.Merge(m, src)
}
func (m *StreamGateMessage) XXX_Size() int {
	return xxx_messageInfo_StreamGateMessage.Size(m)
}
func (m *StreamGateMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamGateMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StreamGateMessage proto.InternalMessageInfo

func (m *StreamGateMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *StreamGateMessage) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *StreamGateMessage) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

type isStreamGateMessage_Kind interface {
	isStreamGateMessage_Kind()
}

type StreamGateMessage_Json struct {
	Json string `protobuf:"bytes,4,opt,name=json,proto3,oneof"`
}

type StreamGateMessage_Protobuf struct {
	Protobuf string `protobuf:"bytes,5,opt,name=protobuf,proto3,oneof"`
}

func (*StreamGateMessage_Json) isStreamGateMessage_Kind() {}

func (*StreamGateMessage_Protobuf) isStreamGateMessage_Kind() {}

func (m *StreamGateMessage) GetKind() isStreamGateMessage_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *StreamGateMessage) GetJson() string {
	if x, ok := m.GetKind().(*StreamGateMessage_Json); ok {
		return x.Json
	}
	return ""
}

func (m *StreamGateMessage) GetProtobuf() string {
	if x, ok := m.GetKind().(*StreamGateMessage_Protobuf); ok {
		return x.Protobuf
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StreamGateMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StreamGateMessage_Json)(nil),
		(*StreamGateMessage_Protobuf)(nil),
	}
}

func init() {
	proto.RegisterType((*StreamGateMessage)(nil), "StreamGateMessage")
}

func init() { proto.RegisterFile("gate_msg.proto", fileDescriptor_a40534712610c588) }

var fileDescriptor_a40534712610c588 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x4f, 0x2c, 0x49,
	0x8d, 0xcf, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x5a, 0xca, 0xc8, 0x25, 0x18,
	0x5c, 0x52, 0x94, 0x9a, 0x98, 0xeb, 0x9e, 0x58, 0x92, 0xea, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e,
	0x2a, 0x24, 0xc4, 0xc5, 0x92, 0x94, 0x9f, 0x52, 0x29, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x13, 0x04,
	0x66, 0x0b, 0xc9, 0x73, 0x71, 0x17, 0xa7, 0x16, 0x95, 0xa5, 0x16, 0xc5, 0xe7, 0x25, 0xe6, 0xa6,
	0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x71, 0x41, 0x84, 0xfc, 0x12, 0x73, 0x53, 0x41, 0x0a,
	0x72, 0x53, 0x4b, 0x32, 0xf2, 0x53, 0x20, 0x0a, 0x98, 0x21, 0x0a, 0x20, 0x42, 0x60, 0x05, 0x22,
	0x5c, 0x2c, 0x59, 0xc5, 0xf9, 0x79, 0x12, 0x2c, 0x20, 0x19, 0x0f, 0x86, 0x20, 0x30, 0x4f, 0x48,
	0x86, 0x8b, 0x03, 0xec, 0x94, 0xa4, 0xd2, 0x34, 0x09, 0x56, 0xa8, 0x0c, 0x5c, 0xc4, 0x89, 0x8d,
	0x8b, 0x25, 0x3b, 0x33, 0x2f, 0x25, 0x89, 0x0d, 0x2c, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0xdf, 0x8a, 0x77, 0x30, 0xc0, 0x00, 0x00, 0x00,
}
